version: '3.7'

services:

  bb:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: bb
    restart: unless-stopped
    ports:
      - "8000"

  nginx:
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./app/frontend/:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - bb:bb
    environment:
      - VIRTUAL_HOST=bloodybrands.com
      - VIRTUAL_PORT=80